//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Lite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Columns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Columns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG_Lite.Columns", typeof(Columns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dod_info.
        /// </summary>
        internal static string Add_Info {
            get {
                return ResourceManager.GetString("Add_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chronione_lokacje.
        /// </summary>
        internal static string Armor_Cover {
            get {
                return ResourceManager.GetString("Armor_Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PZ.
        /// </summary>
        internal static string Armor_Points {
            get {
                return ResourceManager.GetString("Armor_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dostepnosc.
        /// </summary>
        internal static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rodzaj.
        /// </summary>
        internal static string Career_Type {
            get {
                return ResourceManager.GetString("Career_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dod_inf.
        /// </summary>
        internal static string Char_AddInfo {
            get {
                return ResourceManager.GetString("Char_AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wiek.
        /// </summary>
        internal static string Char_Age {
            get {
                return ResourceManager.GetString("Char_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miejsce_urodzenia.
        /// </summary>
        internal static string Char_BirthPlace {
            get {
                return ResourceManager.GetString("Char_BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP.
        /// </summary>
        internal static string Char_EXP {
            get {
                return ResourceManager.GetString("Char_EXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kolor_oczu.
        /// </summary>
        internal static string Char_EyeColor {
            get {
                return ResourceManager.GetString("Char_EyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rodzina.
        /// </summary>
        internal static string Char_Family {
            get {
                return ResourceManager.GetString("Char_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to znaki_szczegolne.
        /// </summary>
        internal static string Char_Features {
            get {
                return ResourceManager.GetString("Char_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plec.
        /// </summary>
        internal static string Char_Gender {
            get {
                return ResourceManager.GetString("Char_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to czczone_bostwo.
        /// </summary>
        internal static string Char_God {
            get {
                return ResourceManager.GetString("Char_God", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kolor_wlosow.
        /// </summary>
        internal static string Char_HairColor {
            get {
                return ResourceManager.GetString("Char_HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wzrost.
        /// </summary>
        internal static string Char_Height {
            get {
                return ResourceManager.GetString("Char_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to historia.
        /// </summary>
        internal static string Char_History {
            get {
                return ResourceManager.GetString("Char_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaburzenia_psychiczne.
        /// </summary>
        internal static string Char_MentalCondition {
            get {
                return ResourceManager.GetString("Char_MentalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blizny_i_rany.
        /// </summary>
        internal static string Char_Scars {
            get {
                return ResourceManager.GetString("Char_Scars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to znak_gwiezdny.
        /// </summary>
        internal static string Char_StarSign {
            get {
                return ResourceManager.GetString("Char_StarSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waga.
        /// </summary>
        internal static string Char_Weight {
            get {
                return ResourceManager.GetString("Char_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schemat_rozwoju.
        /// </summary>
        internal static string Con_AdvStat {
            get {
                return ResourceManager.GetString("Con_AdvStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pancerz.
        /// </summary>
        internal static string Con_Armor {
            get {
                return ResourceManager.GetString("Con_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profesja_wyjsciowa.
        /// </summary>
        internal static string Con_AvailCareer {
            get {
                return ResourceManager.GetString("Con_AvailCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profesja.
        /// </summary>
        internal static string Con_Career {
            get {
                return ResourceManager.GetString("Con_Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_postaci.
        /// </summary>
        internal static string Con_Char {
            get {
                return ResourceManager.GetString("Con_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktualna_wartosc.
        /// </summary>
        internal static string Con_CurrStat {
            get {
                return ResourceManager.GetString("Con_CurrStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaekwipowany.
        /// </summary>
        internal static string Con_Equipped {
            get {
                return ResourceManager.GetString("Con_Equipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bog.
        /// </summary>
        internal static string Con_God {
            get {
                return ResourceManager.GetString("Con_God", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_przedmiotu.
        /// </summary>
        internal static string Con_Item {
            get {
                return ResourceManager.GetString("Con_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rasa.
        /// </summary>
        internal static string Con_Race {
            get {
                return ResourceManager.GetString("Con_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to umiejetnosc.
        /// </summary>
        internal static string Con_Skill {
            get {
                return ResourceManager.GetString("Con_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaklecie.
        /// </summary>
        internal static string Con_Spell {
            get {
                return ResourceManager.GetString("Con_Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wartosc_poczatkowa.
        /// </summary>
        internal static string Con_StartStat {
            get {
                return ResourceManager.GetString("Con_StartStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cecha.
        /// </summary>
        internal static string Con_stat {
            get {
                return ResourceManager.GetString("Con_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zdolnosc.
        /// </summary>
        internal static string Con_Talent {
            get {
                return ResourceManager.GetString("Con_Talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bron.
        /// </summary>
        internal static string Con_Weapon {
            get {
                return ResourceManager.GetString("Con_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opis.
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol.
        /// </summary>
        internal static string God_Symbol {
            get {
                return ResourceManager.GetString("God_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poziom.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nazwa.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cena.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jakosc.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilosc.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to historia.
        /// </summary>
        internal static string Race_History {
            get {
                return ResourceManager.GetString("Race_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wskazowki.
        /// </summary>
        internal static string Race_Tips {
            get {
                return ResourceManager.GetString("Race_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cecha.
        /// </summary>
        internal static string Skill_Stat {
            get {
                return ResourceManager.GetString("Skill_Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typ.
        /// </summary>
        internal static string Skill_Type {
            get {
                return ResourceManager.GetString("Skill_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bonus.
        /// </summary>
        internal static string Spell_Bonus {
            get {
                return ResourceManager.GetString("Spell_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to czas_rzucania.
        /// </summary>
        internal static string Spell_Cast {
            get {
                return ResourceManager.GetString("Spell_Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to czas_trwania.
        /// </summary>
        internal static string Spell_Durat {
            get {
                return ResourceManager.GetString("Spell_Durat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wymagany_poziom_magii.
        /// </summary>
        internal static string Spell_Lvl {
            get {
                return ResourceManager.GetString("Spell_Lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typ_magii.
        /// </summary>
        internal static string Spell_MType {
            get {
                return ResourceManager.GetString("Spell_MType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wymagana_zdolnosc.
        /// </summary>
        internal static string Spell_ReqTal {
            get {
                return ResourceManager.GetString("Spell_ReqTal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wartosc.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kategoria.
        /// </summary>
        internal static string Weapon_Category {
            get {
                return ResourceManager.GetString("Weapon_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sila.
        /// </summary>
        internal static string Weapon_Dmg {
            get {
                return ResourceManager.GetString("Weapon_Dmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zasieg.
        /// </summary>
        internal static string Weapon_Range {
            get {
                return ResourceManager.GetString("Weapon_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przeladowanie.
        /// </summary>
        internal static string Weapon_Reload {
            get {
                return ResourceManager.GetString("Weapon_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cechy.
        /// </summary>
        internal static string Weapon_Treats {
            get {
                return ResourceManager.GetString("Weapon_Treats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obciazenie.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
