//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Lite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG_Lite.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.pancerze;.
        /// </summary>
        internal static string RECORDS_armor {
            get {
                return ResourceManager.GetString("RECORDS_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.profesje;.
        /// </summary>
        internal static string RECORDS_careers {
            get {
                return ResourceManager.GetString("RECORDS_careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.bogowie;.
        /// </summary>
        internal static string RECORDS_gods {
            get {
                return ResourceManager.GetString("RECORDS_gods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.przedmioty;.
        /// </summary>
        internal static string RECORDS_items {
            get {
                return ResourceManager.GetString("RECORDS_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.rasy;.
        /// </summary>
        internal static string RECORDS_races {
            get {
                return ResourceManager.GetString("RECORDS_races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.umiejetnosci;.
        /// </summary>
        internal static string RECORDS_skills {
            get {
                return ResourceManager.GetString("RECORDS_skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.zaklecia;.
        /// </summary>
        internal static string RECORDS_spells {
            get {
                return ResourceManager.GetString("RECORDS_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.cechy;.
        /// </summary>
        internal static string RECORDS_stats {
            get {
                return ResourceManager.GetString("RECORDS_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.zdolnosci;.
        /// </summary>
        internal static string RECORDS_talents {
            get {
                return ResourceManager.GetString("RECORDS_talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.bronie;.
        /// </summary>
        internal static string RECORDS_weapons {
            get {
                return ResourceManager.GetString("RECORDS_weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT dbo.Check_Role();.
        /// </summary>
        internal static string show_role {
            get {
                return ResourceManager.GetString("show_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.pancerz FROM n_uni.profesje p JOIN n_uni.pro_pan l ON p.nazwa = l.profesja WHERE p.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_career_armor {
            get {
                return ResourceManager.GetString("SUPP_career_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.profesja_wyjsciowa FROM n_uni.profesje p JOIN n_uni.pro_pro l ON p.nazwa = l.profesja WHERE p.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_career_career {
            get {
                return ResourceManager.GetString("SUPP_career_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT i.nazwa FROM (n_uni.profesje p JOIN n_uni.pro_prz l ON p.nazwa = l.profesja) JOIN n_uni.przedmioty i ON l.id_przedmiotu =i.id WHERE p.nazwa = &apos;{0}&apos;; .
        /// </summary>
        internal static string SUPP_career_item {
            get {
                return ResourceManager.GetString("SUPP_career_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.umiejetnosc, l.dod_inf FROM n_uni.profesje p JOIN n_uni.pro_umi l ON p.nazwa = l.profesja WHERE p.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_career_skill {
            get {
                return ResourceManager.GetString("SUPP_career_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.cecha, l.wartosc FROM n_uni.profesje p JOIN n_uni.pro_cec l ON p.nazwa = l.profesja WHERE p.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_career_stat {
            get {
                return ResourceManager.GetString("SUPP_career_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.zdolnosc, l.dod_inf FROM n_uni.profesje p JOIN n_uni.pro_zdo l ON p.nazwa = l.profesja WHERE p.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_career_talent {
            get {
                return ResourceManager.GetString("SUPP_career_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.bron FROM n_uni.profesje p JOIN n_uni.pro_bro l ON p.nazwa = l.profesja WHERE p.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_carrer_weapon {
            get {
                return ResourceManager.GetString("SUPP_carrer_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.umiejetnosc, l.dod_inf FROM n_uni.bogowie b JOIN n_uni.bog_umi l ON b.nazwa = l.bog WHERE b.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_god_skill {
            get {
                return ResourceManager.GetString("SUPP_god_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.zdolnosc, l.dod_inf FROM n_uni.bogowie b JOIN n_uni.bog_zdo l ON b.nazwa = l.bog WHERE b.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_god_talent {
            get {
                return ResourceManager.GetString("SUPP_god_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.profesja FROM n_uni.rasy r JOIN n_uni.ras_pro l ON r.nazwa = l.rasa WHERE r.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_race_career {
            get {
                return ResourceManager.GetString("SUPP_race_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.umiejetnosc, l.dod_inf FROM n_uni.rasy r JOIN n_uni.ras_umi l ON r.nazwa = l.rasa WHERE r.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_race_skill {
            get {
                return ResourceManager.GetString("SUPP_race_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.cecha, l.wartosc FROM n_uni.rasy r JOIN n_uni.ras_cec l ON r.nazwa = l.rasa WHERE r.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_race_stat {
            get {
                return ResourceManager.GetString("SUPP_race_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.zdolnosc, l.dod_inf FROM n_uni.rasy r JOIN n_uni.ras_zdo l ON r.nazwa = l.rasa WHERE r.nazwa = &apos;{0}&apos;;.
        /// </summary>
        internal static string SUPP_race_talent {
            get {
                return ResourceManager.GetString("SUPP_race_talent", resourceCulture);
            }
        }
    }
}
