//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Lite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG_Lite.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.pancerze;.
        /// </summary>
        internal static string RECORDS_armor {
            get {
                return ResourceManager.GetString("RECORDS_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.profesje;.
        /// </summary>
        internal static string RECORDS_careers {
            get {
                return ResourceManager.GetString("RECORDS_careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.bogowie;.
        /// </summary>
        internal static string RECORDS_gods {
            get {
                return ResourceManager.GetString("RECORDS_gods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.przedmioty;.
        /// </summary>
        internal static string RECORDS_items {
            get {
                return ResourceManager.GetString("RECORDS_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.rasy;.
        /// </summary>
        internal static string RECORDS_races {
            get {
                return ResourceManager.GetString("RECORDS_races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.umiejetnosci;.
        /// </summary>
        internal static string RECORDS_skills {
            get {
                return ResourceManager.GetString("RECORDS_skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.zaklecia;.
        /// </summary>
        internal static string RECORDS_spells {
            get {
                return ResourceManager.GetString("RECORDS_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.cechy;.
        /// </summary>
        internal static string RECORDS_stats {
            get {
                return ResourceManager.GetString("RECORDS_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.zdolnosci;.
        /// </summary>
        internal static string RECORDS_talents {
            get {
                return ResourceManager.GetString("RECORDS_talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.bronie;.
        /// </summary>
        internal static string RECORDS_weapons {
            get {
                return ResourceManager.GetString("RECORDS_weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT dbo.Check_Role();.
        /// </summary>
        internal static string show_role {
            get {
                return ResourceManager.GetString("show_role", resourceCulture);
            }
        }
    }
}
