//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Lite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG_Lite.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.pancerze (nazwa,opis,dostepnosc,obciazenie,chronione_lokacje,PZ) VALUES (@name,@desc,@availability,@weight,@cover,@points);.
        /// </summary>
        internal static string ADD_armor {
            get {
                return ResourceManager.GetString("ADD_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.pro_pan (pancerz,profesja) VALUES (@armor,@career);.
        /// </summary>
        internal static string ADD_career_armor {
            get {
                return ResourceManager.GetString("ADD_career_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.pro_pro (profesja,profesja_wyjsciowa) VALUES (@career,@possiblecareer);.
        /// </summary>
        internal static string ADD_career_career {
            get {
                return ResourceManager.GetString("ADD_career_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.pro_prz (id_przedmiotu,profesja) VALUES (@item,@career);.
        /// </summary>
        internal static string ADD_career_item {
            get {
                return ResourceManager.GetString("ADD_career_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.pro_umi (umiejetnosc,profesja,dod_inf) VALUES (@skill,@career,@addinfo);.
        /// </summary>
        internal static string ADD_career_skill {
            get {
                return ResourceManager.GetString("ADD_career_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.pro_cec (cecha,profesja,wartosc) VALUES (@stat,@career,@value);.
        /// </summary>
        internal static string ADD_career_stat {
            get {
                return ResourceManager.GetString("ADD_career_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.pro_zdo (zdolnosc,profesja,dod_inf) VALUES (@talent,@career,@addinfo);.
        /// </summary>
        internal static string ADD_career_talent {
            get {
                return ResourceManager.GetString("ADD_career_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.pro_bro (bron,profesja) VALUES (@weapon,@career);.
        /// </summary>
        internal static string ADD_career_weapon {
            get {
                return ResourceManager.GetString("ADD_career_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.profesje (nazwa,rodzaj) VALUES (@name,@type);.
        /// </summary>
        internal static string ADD_careers {
            get {
                return ResourceManager.GetString("ADD_careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO uni.pos_pan (id_postaci,pancerz,jakosc,zaekwipowany,ilosc) VALUES (@charcter,@armor,@quality,@equipped,@quantity);.
        /// </summary>
        internal static string ADD_char_armor {
            get {
                return ResourceManager.GetString("ADD_char_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO uni.pos_bro (id_postaci,id_przedmiotu,jakosc,ilosc,dod_inf) VALUES (@charcter,@item,@quality,@quantity,@addinfo);.
        /// </summary>
        internal static string ADD_char_item {
            get {
                return ResourceManager.GetString("ADD_char_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO uni.pos_umi (id_postaci,umiejetnosc,poziom,dod_inf) VALUES (@charcter,@skill,@level,@addinfo);.
        /// </summary>
        internal static string ADD_char_skill {
            get {
                return ResourceManager.GetString("ADD_char_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO uni.pos_zak (id_postaci,zaklecie) VALUES (@character,@spell);.
        /// </summary>
        internal static string ADD_char_spell {
            get {
                return ResourceManager.GetString("ADD_char_spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO uni.pos_cec (id_postaci,cecha,wartosc_poczatkowa,schemat_rozwoju,aktualna_wartosc) VALUES (@charcter,@stat,@start,@adv,@curr);.
        /// </summary>
        internal static string ADD_char_stat {
            get {
                return ResourceManager.GetString("ADD_char_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO uni.pos_zdo (id_postaci,zdolnosc,dod_inf) VALUES (@charcter,@talent,@addinfo);.
        /// </summary>
        internal static string ADD_char_talent {
            get {
                return ResourceManager.GetString("ADD_char_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO uni.pos_bro (id_postaci,bron,jakosc,zaekwipowany,ilosc) VALUES (@charcter,@weapon,@quality,@equipped,@quantity);.
        /// </summary>
        internal static string ADD_char_weapon {
            get {
                return ResourceManager.GetString("ADD_char_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO uni.postacie (czczone_bostwo,rasa,profesja,nazwa,plec,kolor_oczu,kolor_wlosow,wiek,waga,wzrost,znak_gwiezdny,znaki_szczegolne,miejsce_urodzenia,rodzina,zaburzenia_psychiczne,blizny_i_rany,historia,dod_inf,XP) VALUES (@god,@race,@career,@name,@gender,@eyecolor,@haircolor,@age,@weight,@height,@starsign,@features,@birthplace,@family,@mentalcondition,@scars,@history,@addinfo,@exp);.
        /// </summary>
        internal static string ADD_character {
            get {
                return ResourceManager.GetString("ADD_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.bog_umi (umiejetnosc,bog,dod_inf) VALUES (@skill,@god,@addinfo);.
        /// </summary>
        internal static string ADD_god_skill {
            get {
                return ResourceManager.GetString("ADD_god_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.bog_zdo (zdolnosc,bog,dod_inf) VALUES (@talent,@god,@addinfo);.
        /// </summary>
        internal static string ADD_god_talent {
            get {
                return ResourceManager.GetString("ADD_god_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.bogowie (nazwa,symbol,opis) VALUES (@name,@symbol,@desc);.
        /// </summary>
        internal static string ADD_gods {
            get {
                return ResourceManager.GetString("ADD_gods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.przedmioty (nazwa,opis,dostepnosc,obciazenie,cena) VALUES (@name,@desc,@availability,@weight,@price);.
        /// </summary>
        internal static string ADD_items {
            get {
                return ResourceManager.GetString("ADD_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.ras_pro (profesja,nazwa) VALUES (@career,@race);.
        /// </summary>
        internal static string ADD_race_career {
            get {
                return ResourceManager.GetString("ADD_race_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.ras_umi (umiejetnosc,rasa,dod_inf) VALUES (@skill,@race,@addinfo);.
        /// </summary>
        internal static string ADD_race_skill {
            get {
                return ResourceManager.GetString("ADD_race_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.ras_cec (cecha,rasa,wartosc) VALUES (@stat,@race,@value);.
        /// </summary>
        internal static string ADD_race_stat {
            get {
                return ResourceManager.GetString("ADD_race_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.ras_zdo (zdolnosc,rasa,dod_inf) VALUES (@talent,@race,@addinfo);.
        /// </summary>
        internal static string ADD_race_talent {
            get {
                return ResourceManager.GetString("ADD_race_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.rasy (nazwa,opis,historia,wskazowki) VALUES (@name,@desc,@history,@tips);.
        /// </summary>
        internal static string ADD_races {
            get {
                return ResourceManager.GetString("ADD_races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.umiejetnosci (nazwa,cecha,typ,opis) VALUES (@name,@stat,@type,@desc);.
        /// </summary>
        internal static string ADD_skills {
            get {
                return ResourceManager.GetString("ADD_skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.zak_prz (zaklecie,id_przedmiotu,bonus) VALUES (@spell,@item,@bonus);.
        /// </summary>
        internal static string ADD_spell_item {
            get {
                return ResourceManager.GetString("ADD_spell_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.zaklecia (nazwa,wymagana_zdolnosc,opis,typ_magii,wymagany_poziom_magii,czas_rzucania,czas_trwania) VALUES (@name,@talent,@desc,@type,@level,@casttime,@duration);.
        /// </summary>
        internal static string ADD_spells {
            get {
                return ResourceManager.GetString("ADD_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.cechy (nazwa,opis) VALUES (@name,@desc);.
        /// </summary>
        internal static string ADD_stat {
            get {
                return ResourceManager.GetString("ADD_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.zdo_cec (zdolnosc,cecha,wartosc) VALUES (@talent,@stat,@value);.
        /// </summary>
        internal static string ADD_talent_stat {
            get {
                return ResourceManager.GetString("ADD_talent_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.zdolnosci (nazwa,opis) VALUES (@name,@desc);.
        /// </summary>
        internal static string ADD_talents {
            get {
                return ResourceManager.GetString("ADD_talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO n_uni.bronie (nazwa,cechy,opis,dostepnosc,obciazenie,cena,zasieg,przeladowanie,sila,kategoria) VALUES (@name,@treats,@desc,@availability,@weight,@price,@range,@reload,@damage,@category);.
        /// </summary>
        internal static string ADD_weapons {
            get {
                return ResourceManager.GetString("ADD_weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.pancerz WHERE nazwa = @armor;.
        /// </summary>
        internal static string DELETE_armor {
            get {
                return ResourceManager.GetString("DELETE_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.pro_pan WHERE profesja = @career;.
        /// </summary>
        internal static string DELETE_career_armor {
            get {
                return ResourceManager.GetString("DELETE_career_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.pro_pro WHERE profesja = @career;.
        /// </summary>
        internal static string DELETE_career_career {
            get {
                return ResourceManager.GetString("DELETE_career_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.pro_prz WHERE profesja = @career;.
        /// </summary>
        internal static string DELETE_career_item {
            get {
                return ResourceManager.GetString("DELETE_career_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.pro_umi WHERE profesja = @career;.
        /// </summary>
        internal static string DELETE_career_skill {
            get {
                return ResourceManager.GetString("DELETE_career_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.pro_cec WHERE profesja = @career;.
        /// </summary>
        internal static string DELETE_career_stat {
            get {
                return ResourceManager.GetString("DELETE_career_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.pro_zdo WHERE profesja = @career ;.
        /// </summary>
        internal static string DELETE_career_talent {
            get {
                return ResourceManager.GetString("DELETE_career_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.pro_bro WHERE profesja = @career;.
        /// </summary>
        internal static string DELETE_career_weapon {
            get {
                return ResourceManager.GetString("DELETE_career_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.profesje WHERE nazwa = @career;.
        /// </summary>
        internal static string DELETE_careers {
            get {
                return ResourceManager.GetString("DELETE_careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM uni.pos_pan WHERE id_postaci = @character;.
        /// </summary>
        internal static string DELETE_char_armor {
            get {
                return ResourceManager.GetString("DELETE_char_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM uni.pos_prz WHERE id_postaci = @character;.
        /// </summary>
        internal static string DELETE_char_item {
            get {
                return ResourceManager.GetString("DELETE_char_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM uni.pos_umi WHERE id_postaci = @character;.
        /// </summary>
        internal static string DELETE_char_skill {
            get {
                return ResourceManager.GetString("DELETE_char_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM uni.pos_zak WHERE id_postaci = @character;.
        /// </summary>
        internal static string DELETE_char_spell {
            get {
                return ResourceManager.GetString("DELETE_char_spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM uni.pos_cec WHERE id_postaci = @character;.
        /// </summary>
        internal static string DELETE_char_stat {
            get {
                return ResourceManager.GetString("DELETE_char_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM uni.pos_zdo WHERE id_postaci = @character;.
        /// </summary>
        internal static string DELETE_char_talent {
            get {
                return ResourceManager.GetString("DELETE_char_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM uni.pos_bro WHERE id_postaci = @character;.
        /// </summary>
        internal static string DELETE_char_weapon {
            get {
                return ResourceManager.GetString("DELETE_char_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM uni.postacie WHERE id = @character;.
        /// </summary>
        internal static string DELETE_character {
            get {
                return ResourceManager.GetString("DELETE_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.bog_umi WHERE bog = @god;.
        /// </summary>
        internal static string DELETE_god_skill {
            get {
                return ResourceManager.GetString("DELETE_god_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.bog_zdo WHERE bog = @god;.
        /// </summary>
        internal static string DELETE_god_talent {
            get {
                return ResourceManager.GetString("DELETE_god_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.bogowie WHERE nazwa = @god;.
        /// </summary>
        internal static string DELETE_gods {
            get {
                return ResourceManager.GetString("DELETE_gods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.przedmioty WHERE id = @item;.
        /// </summary>
        internal static string DELETE_items {
            get {
                return ResourceManager.GetString("DELETE_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.ras_pro WHERE nazwa = @race;.
        /// </summary>
        internal static string DELETE_race_career {
            get {
                return ResourceManager.GetString("DELETE_race_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.ras_umi WHERE rasa = @race;.
        /// </summary>
        internal static string DELETE_race_skill {
            get {
                return ResourceManager.GetString("DELETE_race_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.ras_cec WHERE rasa = @race;.
        /// </summary>
        internal static string DELETE_race_stat {
            get {
                return ResourceManager.GetString("DELETE_race_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.ras_zdo WHERE rasa = @race;.
        /// </summary>
        internal static string DELETE_race_talent {
            get {
                return ResourceManager.GetString("DELETE_race_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.rasy WHERE nazwa = @race;.
        /// </summary>
        internal static string DELETE_races {
            get {
                return ResourceManager.GetString("DELETE_races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.umiejetnosci WHERE nazwa = @skill;.
        /// </summary>
        internal static string DELETE_skills {
            get {
                return ResourceManager.GetString("DELETE_skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.zak_prz WHERE zaklecie = @spell;.
        /// </summary>
        internal static string DELETE_spell_item {
            get {
                return ResourceManager.GetString("DELETE_spell_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.zaklecia WHERE nazwa = @spell;.
        /// </summary>
        internal static string DELETE_spells {
            get {
                return ResourceManager.GetString("DELETE_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.cechy WHERE nazwa = @stat;.
        /// </summary>
        internal static string DELETE_stat {
            get {
                return ResourceManager.GetString("DELETE_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.zdo_cec WHERE zdolnosc = @talent;.
        /// </summary>
        internal static string DELETE_talent_stat {
            get {
                return ResourceManager.GetString("DELETE_talent_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.zdolnosci WHERE nazwa = @talent;.
        /// </summary>
        internal static string DELETE_talents {
            get {
                return ResourceManager.GetString("DELETE_talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM n_uni.bronie WHERE nazwa = @weapon;.
        /// </summary>
        internal static string DELETE_weapons {
            get {
                return ResourceManager.GetString("DELETE_weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.pancerze WHERE nazwa = @armor;.
        /// </summary>
        internal static string REC_armor {
            get {
                return ResourceManager.GetString("REC_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.profesje WHERE nazwa = @career;.
        /// </summary>
        internal static string REC_careers {
            get {
                return ResourceManager.GetString("REC_careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM uni.postacie WHERE id = @character;.
        /// </summary>
        internal static string REC_characters {
            get {
                return ResourceManager.GetString("REC_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.bogowie WHERE nazwa = @god;.
        /// </summary>
        internal static string REC_gods {
            get {
                return ResourceManager.GetString("REC_gods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.przedmioty WHERE id = @itemid;.
        /// </summary>
        internal static string REC_items {
            get {
                return ResourceManager.GetString("REC_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.rasy WHERE nazwa = @race;.
        /// </summary>
        internal static string REC_races {
            get {
                return ResourceManager.GetString("REC_races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.umiejetnosci WHERE nazwa = @skill;.
        /// </summary>
        internal static string REC_skills {
            get {
                return ResourceManager.GetString("REC_skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.zaklecia WHERE nazwa = @spell;.
        /// </summary>
        internal static string REC_spells {
            get {
                return ResourceManager.GetString("REC_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.cechy WHERE nazwa = @stat;.
        /// </summary>
        internal static string REC_stats {
            get {
                return ResourceManager.GetString("REC_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.zdolnosci WHERE nazwa = @talent;.
        /// </summary>
        internal static string REC_talents {
            get {
                return ResourceManager.GetString("REC_talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.bronie WHERE nazwa = @weapon;.
        /// </summary>
        internal static string REC_weapons {
            get {
                return ResourceManager.GetString("REC_weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.pancerze;.
        /// </summary>
        internal static string RECORDS_armor {
            get {
                return ResourceManager.GetString("RECORDS_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.profesje;.
        /// </summary>
        internal static string RECORDS_careers {
            get {
                return ResourceManager.GetString("RECORDS_careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM uni.postacie;.
        /// </summary>
        internal static string RECORDS_characters {
            get {
                return ResourceManager.GetString("RECORDS_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.bogowie;.
        /// </summary>
        internal static string RECORDS_gods {
            get {
                return ResourceManager.GetString("RECORDS_gods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.przedmioty;.
        /// </summary>
        internal static string RECORDS_items {
            get {
                return ResourceManager.GetString("RECORDS_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.rasy;.
        /// </summary>
        internal static string RECORDS_races {
            get {
                return ResourceManager.GetString("RECORDS_races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.umiejetnosci;.
        /// </summary>
        internal static string RECORDS_skills {
            get {
                return ResourceManager.GetString("RECORDS_skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.zaklecia;.
        /// </summary>
        internal static string RECORDS_spells {
            get {
                return ResourceManager.GetString("RECORDS_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.cechy;.
        /// </summary>
        internal static string RECORDS_stats {
            get {
                return ResourceManager.GetString("RECORDS_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.zdolnosci;.
        /// </summary>
        internal static string RECORDS_talents {
            get {
                return ResourceManager.GetString("RECORDS_talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM n_uni.bronie;.
        /// </summary>
        internal static string RECORDS_weapons {
            get {
                return ResourceManager.GetString("RECORDS_weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT dbo.Check_Role();.
        /// </summary>
        internal static string show_role {
            get {
                return ResourceManager.GetString("show_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.pancerz FROM n_uni.profesje p JOIN n_uni.pro_pan l ON p.nazwa = l.profesja WHERE p.nazwa = @career;.
        /// </summary>
        internal static string SUPP_career_armor {
            get {
                return ResourceManager.GetString("SUPP_career_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.profesja_wyjsciowa FROM n_uni.profesje p JOIN n_uni.pro_pro l ON p.nazwa = l.profesja WHERE p.nazwa = @career;.
        /// </summary>
        internal static string SUPP_career_career {
            get {
                return ResourceManager.GetString("SUPP_career_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT i.nazwa FROM (n_uni.profesje p JOIN n_uni.pro_prz l ON p.nazwa = l.profesja) JOIN n_uni.przedmioty i ON l.id_przedmiotu =i.id WHERE p.nazwa = @career; .
        /// </summary>
        internal static string SUPP_career_item {
            get {
                return ResourceManager.GetString("SUPP_career_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.umiejetnosc, l.dod_inf FROM n_uni.profesje p JOIN n_uni.pro_umi l ON p.nazwa = l.profesja WHERE p.nazwa = @career;.
        /// </summary>
        internal static string SUPP_career_skill {
            get {
                return ResourceManager.GetString("SUPP_career_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.cecha, l.wartosc FROM n_uni.profesje p JOIN n_uni.pro_cec l ON p.nazwa = l.profesja WHERE p.nazwa = @career;.
        /// </summary>
        internal static string SUPP_career_stat {
            get {
                return ResourceManager.GetString("SUPP_career_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.zdolnosc, l.dod_inf FROM n_uni.profesje p JOIN n_uni.pro_zdo l ON p.nazwa = l.profesja WHERE p.nazwa = @career;.
        /// </summary>
        internal static string SUPP_career_talent {
            get {
                return ResourceManager.GetString("SUPP_career_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.bron FROM n_uni.profesje p JOIN n_uni.pro_bro l ON p.nazwa = l.profesja WHERE p.nazwa = @career;.
        /// </summary>
        internal static string SUPP_carrer_weapon {
            get {
                return ResourceManager.GetString("SUPP_carrer_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.pancerz, l.jakosc, l.zaekwipowany, l.ilosc FROM uni.postacie p JOIN uni.pos_pan l ON l.id_postaci = p.id WHERE p.id = @character;.
        /// </summary>
        internal static string SUPP_char_armor {
            get {
                return ResourceManager.GetString("SUPP_char_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT i.nazwa, l.dod_inf, l.jakosc, l.ilosc FROM (uni.postacie p JOIN uni.pos_prz l ON l.id_postaci = p.id) JOIN n_uni.przedmioty i ON i.id = l.id_przedmiotu WHERE p.id = @character;.
        /// </summary>
        internal static string SUPP_char_item {
            get {
                return ResourceManager.GetString("SUPP_char_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.umiejetnosc, l.poziom, l.dod_inf FROM uni.postacie p JOIN uni.pos_umi l ON l.id_postaci = p.id WHERE p.id = @character;.
        /// </summary>
        internal static string SUPP_char_skill {
            get {
                return ResourceManager.GetString("SUPP_char_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.zaklecie FROM uni.postacie p JOIN uni.pos_zak l ON l.id_postaci = p.id WHERE p.id = @character;.
        /// </summary>
        internal static string SUPP_char_spell {
            get {
                return ResourceManager.GetString("SUPP_char_spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.cecha, l.wartosc_poczatkowa, l.schemat_rozwoju, l.aktualna_wartosc FROM uni.postacie p JOIN uni.pos_cec l ON l.id_postaci = p.id WHERE p.id = @character;.
        /// </summary>
        internal static string SUPP_char_stat {
            get {
                return ResourceManager.GetString("SUPP_char_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.zdolnosc, l.dod_inf FROM uni.postacie p JOIN uni.pos_zdo l ON l.id_postaci = p.id WHERE p.id = @character;.
        /// </summary>
        internal static string SUPP_char_talent {
            get {
                return ResourceManager.GetString("SUPP_char_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.bron, l.jakosc, l.zaekwipowany, l.ilosc FROM uni.postacie p JOIN uni.pos_bro l ON l.id_postaci = p.id WHERE p.id = @character;.
        /// </summary>
        internal static string SUPP_char_weapon {
            get {
                return ResourceManager.GetString("SUPP_char_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.umiejetnosc, l.dod_inf FROM n_uni.bogowie b JOIN n_uni.bog_umi l ON b.nazwa = l.bog WHERE b.nazwa = @god;.
        /// </summary>
        internal static string SUPP_god_skill {
            get {
                return ResourceManager.GetString("SUPP_god_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.zdolnosc, l.dod_inf FROM n_uni.bogowie b JOIN n_uni.bog_zdo l ON b.nazwa = l.bog WHERE b.nazwa = @god;.
        /// </summary>
        internal static string SUPP_god_talent {
            get {
                return ResourceManager.GetString("SUPP_god_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.profesja FROM n_uni.rasy r JOIN n_uni.ras_pro l ON r.nazwa = l.nazwa WHERE r.nazwa = @race;.
        /// </summary>
        internal static string SUPP_race_career {
            get {
                return ResourceManager.GetString("SUPP_race_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.umiejetnosc, l.dod_inf FROM n_uni.rasy r JOIN n_uni.ras_umi l ON r.nazwa = l.rasa WHERE r.nazwa = @race;.
        /// </summary>
        internal static string SUPP_race_skill {
            get {
                return ResourceManager.GetString("SUPP_race_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.cecha, l.wartosc FROM n_uni.rasy r JOIN n_uni.ras_cec l ON r.nazwa = l.rasa WHERE r.nazwa = @race;.
        /// </summary>
        internal static string SUPP_race_stat {
            get {
                return ResourceManager.GetString("SUPP_race_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.zdolnosc, l.dod_inf FROM n_uni.rasy r JOIN n_uni.ras_zdo l ON r.nazwa = l.rasa WHERE r.nazwa = @race;.
        /// </summary>
        internal static string SUPP_race_talent {
            get {
                return ResourceManager.GetString("SUPP_race_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT i.nazwa,l.bonus FROM (n_uni.zaklecia z JOIN n_uni.zak_prz l ON z.nazwa = l.zaklecie) JOIN n_uni.przedmioty i ON l.id_przedmiotu =i.id WHERE z.nazwa = @spell;.
        /// </summary>
        internal static string SUPP_spell_item {
            get {
                return ResourceManager.GetString("SUPP_spell_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT l.cecha, l.wartosc FROM n_uni.zdolnosci t JOIN n_uni.zdo_cec l ON t.nazwa = l.zdolnosc WHERE t.nazwa = @talent;.
        /// </summary>
        internal static string SUPP_talent_stat {
            get {
                return ResourceManager.GetString("SUPP_talent_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE dbo.del_character(@character);.
        /// </summary>
        internal static string USER_Del_character {
            get {
                return ResourceManager.GetString("USER_Del_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM dbo.get_character(@character);.
        /// </summary>
        internal static string USER_Get_Character {
            get {
                return ResourceManager.GetString("USER_Get_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM dbo.get_characters();.
        /// </summary>
        internal static string USER_Get_characters {
            get {
                return ResourceManager.GetString("USER_Get_characters", resourceCulture);
            }
        }
    }
}
